### ISSUE TITLE
Space before text for Temp & Humi by sonoff-sc

### ISSUE THREAD

**Issue by mike2nl** [reloxx13/Sonoff-Tasmota-Modified#4]
_A clear and concise description of what the bug is._

When you take a look at the table for the sensor values and text
for a SOnOff-SC envoirment module you can see a space before the
text for Temperature and Humidity. The rest of the text is ok without
a space character before the text.

Also, make sure these boxes are checked [x] before submitting your issue - Thank you!

- [x ] Searched the problem in issues and in the wiki
--> Yes and nothing found ;-)

- [x ] Hardware used : 
--> SONOFF-SC with an external AM2302 T&H sensor
Fugure 1:
![sensor external](https://user-images.githubusercontent.com/5562918/43683187-e4dbf0ea-9886-11e8-81f2-10d14b56611a.png)

- [x ] Provide the output of command ``status 0`` :
--> NOT needed in this case

**To Reproduce**
_Steps to reproduce the behavior:_
->Open the web page for the sonoff-sc module
->Wait 3 or 4 seconds to get the first values
->Cut the network connection
->Goto Inspect the web page (CTRL+SHIFT+I)
->Open the table defines near _<div id='l1' name='l1'>_
->Open the <tr> defines
->Take a look at Temperature and Humidity
->You can see a space char before these both text's 

**Expected behavior**
_A clear and concise description of what you expected to happen._
No speace char before these both text's

**Screenshots**
_If applicable, add screenshots to help explain your problem._
Figure 2:
![sonoff-sc table space in temp and humidity 2nd](https://user-images.githubusercontent.com/5562918/43683130-a8fc3b62-9885-11e8-928c-d58ba0df9587.PNG)

It's not really a bug in the meaning but we can save 2 bytes ;-) for the 
webserver. And in a place where every byte counts here are two more.

**(Please, remember to close the issue when the problem has been addressed)**

**Comment by reloxx13** [comment]
the sensor name is missing, thats why their is a space

i18n.h line 522 and following
`const char HTTP_SNS_TEMP[] PROGMEM = "%s{s}%s " D_TEMPERATURE "{m}%s°%c{e}"; `

this is generic (used by all sensors), i think writing an if around would use more space than let it as it is, since the space still has to be there for the other sensors.

**Comment by mike2nl** [comment]
Ah yes, i see. Did'nt see that line, jesus. You are 100% right and around code 
costs more space which we have (not much) on the chip. Very good point. So i will close it.
